### ISSUE TITLE
alinear el  glyphicon-triangle-bottom en el home

### ISSUE THREAD

**Issue by jlopezvi** [jlopezvi/Consensus#15]
glyphicon glyphicon-triangle-bottom

Hay que llevar el triangulito un poco más a la izquierda (ojo a que quede bien en todos los navegadores)
![capture d ecran 2018-02-11 a 21 46 10](https://user-images.githubusercontent.com/6387427/36078349-2482b35a-0f75-11e8-9079-966d9818ab56.png)
25e

**Comment by nicol655** [comment]
Ya esta para pruebas.
