### ISSUE TITLE
Add button  Follow/Unfollow to participants

### ISSUE THREAD

**Issue by jlopezvi** [jlopezvi/Consensus#21]
en el mismo sitio que la "tuerca" de configuración del propio usuario.  10e.

**Comment by nicol655** [comment]
Ya está hecho este task, revisar y probar la funcionalidad de los botones al seguir / dejar de seguir un participante desde tu pagina.

Aparte, acomodé graficamente el posicionamiento de la informacion del participante. Donde indica la cantidad de ideas activas, seguidores y los que sigue.
