### ISSUE TITLE
Followers, following, change buttons

### ISSUE THREAD

**Issue by jlopezvi** [jlopezvi/Consensus#7]
![capture d ecran 2017-11-22 a 10 17 26](https://user-images.githubusercontent.com/6387427/33119206-8ac1d6ec-cf6e-11e7-9522-36732eb8c5af.png)

Change the follow buttons. 25e

**Comment by nicol655** [comment]
Está listo en el listado de los Followings, Followers y en el listado de usuarios publicos.
Se cambia el texto en el boton del listado de usuarios publicos de Follow/Unfollow a Follow/Stop Following.
Quedo a la espera de la modificacion del API que devuelve al usuario privado, se necesita que diga si el usuario conectado sigue o no al usuario privado (previamente buscado por el email).
Se acomodó el error que al hacer click sobre dichos botones desaparece el borde del mismo.
